version: '3.7'
services:
  snipe:
    image: snipe/snipe-it:latest
    ports:
      - 8000:80
    env_file: ./snipe/env-file
    volumes:
      - './data:/var/lib/snipeit'
    links:
      - snipedb:snipedb
      - redis
  snipedb:
    image: mysql:5.6
    env_file: ./snipe/.env
